### ISSUE TITLE
Could not compile release v1.18.12: ftp.pcre.org unreachable 

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry-incubator/backup-and-restore-sdk-release#265] opened 2021-07-13 08:08 UTC
Hello,

I'm having trouble compiling latest (`v1.18.12`) version of backup-and-restore-sdk-release in my environment.  

In package `database-backup-restorer-mariadb`, while compiling mariadb `v10.6.3`, the cmake tries to fetch pcre2 library from `ftp.pcre.org`. My compilation vms do not have direct internet access thus the process fails.

Cmake uses libcurl internally therefore should be compatible with proxy environment settings. Does anyone know a way to set proxy settings to bosh compilation vms ?

Alternatively, would it be possible to ship the release with libpcre2 pre-installed by another package and with mariadb compiled with `-DWITH_PRCE=system` ? 

Thanks a lot,

**Comment by kirederik** [comment] 2021-07-13 10:09
Hello @psycofdj

Thanks for raising this issue.
We'll take a look at it and get back to you soon.

**Comment by kirederik** [comment] 2021-07-15 08:23
We added libpcre2 to the sdk release. We plan to release a new version shortly. I'll close this issue when that happens.

**Comment by kirederik** [comment] 2021-07-19 16:39
v1.18.3 is out!

Let us know if you find any problems.

Thanks!

**Comment by kirederik** [comment] 2021-07-19 18:32
It looks like the issue is still there on .13. We'll reopen this one

**Comment by psycofdj** [comment] 2021-07-19 18:38
I confirm that the issue is still here

```
...
-- Looking for include files curses.h, term.h
-- Looking for include files curses.h, term.h - found
-- Looking for pcre2_match_8 in pcre2-8
-- Looking for pcre2_match_8 in pcre2-8 - not found
-- Configuring incomplete, errors occurred!
See also "/var/vcap/data/compile/database-backup-restorer-mariadb/mariadb-10.6.3/bld/CMakeFiles/CMakeOutput.log".
See also "/var/vcap/data/compile/database-backup-restorer-mariadb/mariadb-10.6.3/bld/CMakeFiles/CMakeError.log".
, Stderr: + MARIADB_VERSION=10.6.3
++ pwd
+ MY_DIR=/var/vcap/data/compile/database-backup-restorer-mariadb
+ tar xzf mariadb/mariadb-10.6.3.tar.gz
+ set -e
+ cd mariadb-10.6.3
+ mkdir bld
+ cd bld
+ cmake .. -DCMAKE_INSTALL_PREFIX=/var/vcap/packages/database-backup-restorer-mariadb -DWITHOUT_SERVER=ON -DWITH_SSL=system -DWITH_WSREP=ON -DWITH_INNODB_DISALLOW_WRITES=1 -DWITH_PCRE=system
CMake Error at cmake/pcre.cmake:72 (MESSAGE):
  system pcre2-8 library is not found or unusable
Call Stack (most recent call first):
  CMakeLists.txt:394 (CHECK_PCRE)
...
```

Let me know if there is anything I can do to help.

**Comment by peterhaochen47** [comment] 2021-07-22 23:13
This is also happening for us for `v1.18.13`:

**Comment by psycofdj** [comment] 2021-07-23 16:17
`v1.18.14` compiles fine and this issue can be closed.
Thank you for your work !

**Comment by kirederik** [comment] 2021-07-23 16:29
Awesome, thanks for the feedback!

**Closed by kirederik** 2021-07-23 16:29 UTC
Labels: unscheduled
